// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';
import { envConfig } from './src/core/config/env.config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: envConfig.DATABASE_URL,
    shadowDatabaseUrl: envConfig.DIRECT_URL,
  },
});
